<a href="https://colab.research.google.com/github/PRIYA-P14/Ecommerce_Discount_Analysis/blob/main/Ecommerce_Discount_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
import os

os.listdir('/content/drive/MyDrive')

['Colab Notebooks',
 'Classroom',
 'PRIYA.gdoc',
 'CIA II - Exercises with Answers - TE.gdoc',
 'Exercise3 - String Manipulation.gdoc',
 'Priya P .pdf',
 'datas',
 '24CS179-Priya.pdf',
 'Igen.jpg',
 'PASSPORT.jpeg',
 'Screenshot_2026_0123_165615.png',
 'IMG-20260218-WA0005.jpg',
 'IMG-20260218-WA0017.jpg',
 'WhatsApp Image 2026-02-24 at 2.23.50 PM.jpeg',
 'payment.jpeg',
 'poster.jpeg',
 'Untitled form.gform',
 'IMG-20260325-WA0017.jpg',
 'IMG-20260325-WA0018.jpg',
 'IMG-20260325-WA0019.jpg',
 'NOC26MG51S363700187.pdf',
 'NPTEL..',
 'FSD 1 (1).pdf',
 'FSD 1.pdf',
 'UDEMY_FSD.jpeg',
 'cont_merged.pdf',
 '24CS179_Priya_Resume.pdf',
 'final_training_dataset',
 'Copy of Online Shopping sequence diagram.png',
 'student_marks.csv',
 '.ipynb_checkpoints',
 'student_marks.json',
 'students_marks.xlsx',
 'Fee receipt.jpg',
 'Book1.csv',
 'TRUCK POOLING SYSTEM.pdf',
 'Priya NDA_copy.pdf',
 'SmartAIthon 2026 - Round 1 PPT Template.pptx.pdf',
 'Gmail - Invitation to the Top 100 Finalists – AI for Social Impact Challenge 2026.pdf',
 'IMG-20260713-WA0010 (1).jpg',
 'IMG-20260713-WA0010.jpg',
 'Breakdown_Prediction',
 'Professional certificates',
 'Endorsement form for NIT.jpeg',
 'resourse_agent.docx',
 'crop_agent.docx',
 'market_agent.docx',
 'Exp No 5.gdoc',
 'Copy of 24CS179_Priya_Resume.pdf',
 '24CS179-Resume',
 '24CS179-Self_Intro',
 'Screenshot 2026-08-12 162016.png',
 'Linguaskills_payment.jpg',
 'Aadhar Card.jpeg',
 'hospital_resource_allocation_mock_150.csv',
 'Hospital_Resource_Allocation',
 'Ecommerce_Discount_Analysis']

In [9]:
os.listdir('/content/drive/MyDrive/Ecommerce_Discount_Analysis')

['Dataset']

In [10]:
os.listdir('/content/drive/MyDrive/Ecommerce_Discount_Analysis/Dataset')

['ecommerce_discount_analysis_mock_150.csv']

In [11]:
import pandas as pd

file_path = "/content/drive/MyDrive/Ecommerce_Discount_Analysis/Dataset/ecommerce_discount_analysis_mock_150.csv"

df = pd.read_csv(file_path)

df.head()

,Order_ID,Product_Category,Original_Price,Discount,Selling_Price,Quantity,Logistics_Cost,Customer_ID,Promotion_Period
0,ORD0001,Beauty,2074.67,10,1867.21,6,537.47,CUST1011,After Promotion
1,ORD0002,Home & Kitchen,4862.76,10,4376.48,3,674.32,CUST1060,After Promotion
2,ORD0003,Sports,3476.51,10,3128.86,6,892.30,CUST1042,During Promotion
3,ORD0004,Beauty,1580.44,0,1580.44,3,286.06,CUST1052,After Promotion
4,ORD0005,Electronics,19514.69,0,19514.69,1,434.25,CUST1020,Before Promotion

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
from scipy.stats import pearsonr

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

Load the dataset

In [15]:
df = pd.read_csv(file_path)

df.head()

,Order_ID,Product_Category,Original_Price,Discount,Selling_Price,Quantity,Logistics_Cost,Customer_ID,Promotion_Period
0,ORD0001,Beauty,2074.67,10,1867.21,6,537.47,CUST1011,After Promotion
1,ORD0002,Home & Kitchen,4862.76,10,4376.48,3,674.32,CUST1060,After Promotion
2,ORD0003,Sports,3476.51,10,3128.86,6,892.30,CUST1042,During Promotion
3,ORD0004,Beauty,1580.44,0,1580.44,3,286.06,CUST1052,After Promotion
4,ORD0005,Electronics,19514.69,0,19514.69,1,434.25,CUST1020,Before Promotion

In [16]:
df.shape

(150, 9)

In [17]:
df.columns

Index(['Order_ID', 'Product_Category', 'Original_Price', 'Discount',
       'Selling_Price', 'Quantity', 'Logistics_Cost', 'Customer_ID',
       'Promotion_Period'],
      dtype='object')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          150 non-null    object
 1   Product_Category  150 non-null    object
 2   Original_Price    150 non-null    float64
 3   Discount          150 non-null    int64
 4   Selling_Price     150 non-null    float64
 5   Quantity          150 non-null    int64
 6   Logistics_Cost    150 non-null    float64
 7   Customer_ID       150 non-null    object
 8   Promotion_Period  150 non-null    object
dtypes: float64(3), int64(2), object(4)
memory usage: 10.7+ KB